#!/usr/bin/env python3
"""Generate build/plugins.s from plugins/manifest.json (static plugins, M6).

Usage:
    tools/gen-plugins.py > build/plugins.s
    tools/gen-plugins.py --macho > build/plugins-mac.s
    tools/gen-plugins.py --list          # "<name>:<source>" per source, for the Makefile

Manifest schema (kept deliberately simple):

    {"plugins": [{"name": "example_c", "sources": ["plugins/example_c/plugin.c"]}]}

`name` must be a C identifier: it selects the exported init symbol
`opcode_plugin_init_<name>` that the Makefile produces with
`-Dopcode_plugin_init=opcode_plugin_init_<name>`.

The table's references are assembly symbol names, not C names.  On Mach-O a C
compiler gives the definition a leading underscore (`_opcode_plugin_init_x`),
but a hand-written reference does not get one, so `--macho` emits the
underscored references the Darwin link needs.  Linux is the default.

Output is deterministic (manifest order, no timestamps): a table of
{init, name, manifest index} records plus `opcode_plugin_count`. The host
loader (src/ext/plugin.s) walks it.  With zero plugins the count is 0 and the
table is empty; the loader skips silently.
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST_PATH = os.path.join(ROOT, "plugins", "manifest.json")

NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def fail(message):
    sys.stderr.write("gen-plugins: %s\n" % message)
    sys.exit(1)


def asm_asciz(value):
    """Escape a Python string for a GNU as .asciz directive."""
    out = []
    for ch in value:
        code = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif 0x20 <= code < 0x7F:
            out.append(ch)
        else:
            for byte in ch.encode("utf-8"):
                out.append("\\%03o" % byte)
    return "".join(out)


def load_plugins():
    try:
        with open(MANIFEST_PATH, "r", encoding="utf-8") as handle:
            data = json.load(handle)
    except OSError as exc:
        fail("cannot read %s: %s" % (MANIFEST_PATH, exc))
    except ValueError as exc:
        fail("%s is not valid JSON: %s" % (MANIFEST_PATH, exc))

    plugins = data.get("plugins") if isinstance(data, dict) else None
    if not isinstance(plugins, list):
        fail('%s must be an object with a "plugins" array' % MANIFEST_PATH)

    clean = []
    seen = set()
    for index, plugin in enumerate(plugins):
        if not isinstance(plugin, dict):
            fail("plugins[%d] is not an object" % index)
        name = plugin.get("name")
        if not isinstance(name, str) or not NAME_RE.match(name):
            fail("plugins[%d].name must be a C identifier" % index)
        if name in seen:
            fail("duplicate plugin name %r" % name)
        seen.add(name)
        sources = plugin.get("sources")
        if not isinstance(sources, list) or not sources:
            fail("plugins[%d].sources must be a non-empty array" % index)
        for source in sources:
            if not isinstance(source, str) or not source:
                fail("plugins[%d].sources entries must be non-empty strings" % index)
        clean.append({"name": name, "sources": list(sources)})
    return clean


def list_sources(plugins):
    for plugin in plugins:
        for source in plugin["sources"]:
            sys.stdout.write("%s:%s\n" % (plugin["name"], source))


def emit_asm(plugins, macho=False):
    # A Mach-O C definition carries a leading underscore, so the references the
    # table makes to the plugin inits need one too; Linux has no prefix.
    prefix = "_" if macho else ""
    lines = []
    lines.append("# generated by tools/gen-plugins.py: do not edit")
    lines.append("# %d plugin(s) from plugins/manifest.json" % len(plugins))
    lines.append(".section .rodata")
    for index, plugin in enumerate(plugins):
        lines.append('.Lplug_name_%d: .asciz "%s"' % (index, asm_asciz(plugin["name"])))
    lines.append("")
    lines.append(".p2align 3")
    lines.append(".globl opcode_plugin_count")
    lines.append("opcode_plugin_count: .quad %d" % len(plugins))
    lines.append("")
    for plugin in plugins:
        lines.append(".extern %sopcode_plugin_init_%s" % (prefix, plugin["name"]))
    lines.append("")
    lines.append(".p2align 3")
    lines.append(".globl opcode_plugin_table")
    lines.append("opcode_plugin_table:")
    for index, plugin in enumerate(plugins):
        lines.append("    # %s" % plugin["name"])
        lines.append("    .quad %sopcode_plugin_init_%s" % (prefix, plugin["name"]))
        lines.append("    .quad .Lplug_name_%d" % index)
        lines.append("    .quad %d" % index)
    lines.append("")
    lines.append(".text")
    sys.stdout.write("\n".join(lines) + "\n")


def main(argv):
    plugins = load_plugins()
    args = argv[1:]
    macho = False
    if args and args[0] == "--macho":
        macho = True
        args = args[1:]
    if args and args[0] == "--list":
        list_sources(plugins)
        return
    if args:
        fail("unknown argument %r (use --macho or --list)" % args[0])
    emit_asm(plugins, macho=macho)


if __name__ == "__main__":
    main(sys.argv)
