#!/bin/sh
# embeds runtime assets into build/assets.s (version, cacert bundle, later:
# catalog/themes/prompts).  .incbin paths are relative to the repository root:
# the build always assembles from there.
set -e
cd "$(dirname "$0")/.."
v=$(cat VERSION)
cat <<EOF
# generated by tools/gen-assets.sh - do not edit
.section .rodata
.globl opcode_version
opcode_version: .asciz "$v"

# Mozilla CA bundle (MPL-2.0), vendored as third_party/cacert.pem.
# The explicit NUL is what makes mbedtls_x509_crt_parse() treat the buffer as
# PEM; opcode_cacert_end includes it, so the length passed to mbedTLS is
# opcode_cacert_end - opcode_cacert.
.globl opcode_cacert
opcode_cacert:
.incbin "third_party/cacert.pem"
.byte 0
.globl opcode_cacert_end
opcode_cacert_end:
.text
EOF
