#!/usr/bin/env python3
"""Generate build/catalog.s from runtime/catalog.json.

Usage: tools/gen-catalog.py > build/catalog.s

Pure Python 3 stdlib, no dependencies.  Output is deterministic: models are
sorted by provider and then id; strings are emitted once per distinct value in
first-use order.  Each record is exactly MD_SIZE (56) bytes as defined by
src/core/core.inc:

    .quad id, name, api, provider, base
    .long context_window, max_tokens, flags, 0
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATALOG_PATH = os.path.join(ROOT, "runtime", "catalog.json")

MDF_REASONING = 1
MDF_IMAGE = 2
MDF_NO_KEY = 4
MDF_DEFAULT = 8

FIELDS = ("id", "name", "api", "provider", "base")
REQUIRED_STRINGS = FIELDS
REQUIRED_INTS = ("context_window", "max_tokens")


def fail(message):
    sys.stderr.write("gen-catalog: %s\n" % message)
    sys.exit(1)


def asm_asciz(value):
    """Escape a Python string for a GNU as .asciz directive."""
    out = []
    for ch in value:
        code = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif 0x20 <= code < 0x7F:
            out.append(ch)
        else:
            for byte in ch.encode("utf-8"):
                out.append("\\%03o" % byte)
    return "".join(out)


def load_models():
    try:
        with open(CATALOG_PATH, "r", encoding="utf-8") as handle:
            data = json.load(handle)
    except OSError as exc:
        fail("cannot read %s: %s" % (CATALOG_PATH, exc))
    except ValueError as exc:
        fail("%s is not valid JSON: %s" % (CATALOG_PATH, exc))

    models = data.get("models") if isinstance(data, dict) else None
    if not isinstance(models, list) or not models:
        fail('%s must be an object with a non-empty "models" array' % CATALOG_PATH)

    clean = []
    for index, model in enumerate(models):
        if not isinstance(model, dict):
            fail("models[%d] is not an object" % index)
        for key in REQUIRED_STRINGS:
            value = model.get(key)
            if not isinstance(value, str) or not value:
                fail('models[%d].%s must be a non-empty string' % (index, key))
        for key in REQUIRED_INTS:
            value = model.get(key)
            if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
                fail("models[%d].%s must be a positive integer" % (index, key))
        flags = 0
        if model.get("reasoning", False):
            flags |= MDF_REASONING
        if model.get("image", True):
            flags |= MDF_IMAGE
        if model.get("no_key", False):
            flags |= MDF_NO_KEY
        if model.get("default", False):
            flags |= MDF_DEFAULT
        entry = {key: model[key] for key in FIELDS}
        entry["context_window"] = model["context_window"]
        entry["max_tokens"] = model["max_tokens"]
        entry["flags"] = flags
        clean.append(entry)

    clean.sort(key=lambda model: (model["provider"], model["id"]))
    return clean


def main():
    models = load_models()

    labels = {}
    strings = []
    for model in models:
        for field in FIELDS:
            key = (field, model[field])
            if key not in labels:
                labels[key] = ".Lcat_%s_%d" % (field, len(labels))
                strings.append((labels[key], model[field]))

    lines = []
    lines.append("# generated by tools/gen-catalog.py: do not edit")
    lines.append("# %d models from runtime/catalog.json, sorted by provider then id" % len(models))
    lines.append(".section .rodata")
    for label, value in strings:
        lines.append('%s: .asciz "%s"' % (label, asm_asciz(value)))
    lines.append("")
    lines.append(".p2align 3")
    lines.append(".globl opcode_catalog_count")
    lines.append("opcode_catalog_count: .quad %d" % len(models))
    lines.append("")
    lines.append(".p2align 3")
    lines.append(".globl opcode_catalog")
    lines.append("opcode_catalog:")
    for model in models:
        lines.append("    # %s/%s" % (model["provider"], model["id"]))
        for field in FIELDS:
            lines.append("    .quad %s" % labels[(field, model[field])])
        lines.append("    .long %d" % model["context_window"])
        lines.append("    .long %d" % model["max_tokens"])
        lines.append("    .long %d" % model["flags"])
        lines.append("    .long 0")
    lines.append("")
    lines.append(".text")

    sys.stdout.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
